  test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-pretest
          path: ./

      - name: run unit test
        run: go test ./...

      - name: Trivy FS Scan (Code Base)
        uses: aquasecurity/trivy-action@v0.14.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 1
